version: "3.9"

services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: trantor
      POSTGRES_PASSWORD: trantor
      POSTGRES_DB: trantor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
